# Generated by Django 4.2.3 on 2023-07-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Board',
        ),
    ]
